name: JobRadar Daily Scraper

# Menentukan kapan script dijalankan
on:
  schedule:
    # Berjalan setiap jam 19:00 UTC, yang sama dengan jam 02:00 pagi WIB (Waktu Indonesia Barat)
    - cron: "0 19 * * *"
  # Memungkinkan kita menekan tombol "Run" secara manual di menu GitHub Actions
  workflow_dispatch:

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest

    steps:
      # 1. Mengambil kode terbaru dari repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Menyiapkan Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Sesuaikan dengan versimu

      # 3. Menginstal dependensi (Pastikan requirements.txt sudah di-push ke GitHub)
      - name: Install Dependencies
        run: |
          cd jobradar_data_pipeline
          pip install -r requirements.txt

      # 4. Menjalankan Pipeline Utama
      - name: Run Scraper Pipeline
        env:
          # Masukkan variabel rahasia ini di menu Settings > Secrets and variables > Actions di GitHub
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          cd jobradar_data_pipeline
          python main.py
