name: JobRadar Daily Scraper

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest

    # 1. Mengatur folder kerja default untuk seluruh job ini
    defaults:
      run:
        working-directory: ./jobradar_data_pipeline

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 2. Debugging: Cetak daftar file untuk memastikan folder dan isinya ada
      - name: Debugging - Cek Isi Folder Pipeline
        run: ls -la

      # 3. Instalasi tanpa perlu 'cd' lagi karena working-directory sudah di-set
      - name: Install Dependencies
        run: pip install -r requirements.txt

      # 4. Eksekusi Scraper
      - name: Run Scraper Pipeline
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py
